server:
  port: 8081

ecommerce:
  jwt:
    secret: change-me-in-prod
    expiration-ms: 86400000

spring:
  application:
    name: auth-service
  app:
    jwtSecret: ${ecommerce.jwt.secret}
    jwtExpirationMs: ${ecommerce.jwt.expiration-ms}
    cookieName: jwt-cookie
