server:
  port: 8081

spring:
  application:
    name: order-service
  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
